MAX_TRAILS = 21

READ_SAMPLE = False
BEAUTY_SPEED = True
SERIAL_BUTTON = True

MAX_ATTEMPTS = 10

MAX_HEIGHT_NEEDED = 2  # cm
MAX_LENGTH_NEEDED = 2
MIN_HEIGHT_NEEDED = 3 # cm
MIN_LENGTH_NEEDED = 3
POSITION_BUTTON = (0,15,1.5)

fs = 120
fc = 10

ORDER_FILTER = 2  # 4
SPEED_FILTER = True

SENSORS_USED = 2

THRESHOLD_BOTH_HANDS = 20
THRESHOLD_CHANGED_HANDS_MEAS = 20
SPEED_THRESHOLD = 0.05

HEIGHT_BOX = 15

NUMBER_EVENTS = 6
COLORS_EVENT = ['blue', 'purple', 'orange', 'yellow', 'pink', 'black']
LABEL_EVENT = ['e1', 'e2', 'e3', 'e4', 'e5', 'e6']
